-- 添加邮件服务配置字段
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_service_type VARCHAR(10) DEFAULT 'smtp';
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_secure BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_pass TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_from VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS resend_api_key TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resend_from VARCHAR(255);

-- 添加邮箱字段（如果不存在）
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);

-- 添加验证码相关字段（如果不存在）
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_code VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_expires_at TIMESTAMP WITH TIME ZONE;

-- 创建邮箱唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email) WHERE email IS NOT NULL;