-- 添加WebDAV备份配置字段
ALTER TABLE users ADD COLUMN IF NOT EXISTS webdav_url VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS webdav_username VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS webdav_password TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS webdav_auto_backup BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS webdav_backup_interval INTEGER DEFAULT 24;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_backup_at TIMESTAMP WITH TIME ZONE;
